### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by heivo** [Lothrik/diablo4-build-calc#1]
Hi,

great work so far.

I have a question: where did you get the data from? Is it publicly available somewhere or did you put this all together on your own?

Thanks

**Comment by Lothrik** [comment]
>I have a question: where did you get the data from?

It's all datamined from the game directly. You either need a copy of the already-decrypted assets, or a copy of the game and a decryption key to datamine anything useful.

I originally got the [tree data](https://github.com/Lothrik/diablo4-build-calc/tree/master/parser/tree) from someone else over Discord.

I've been working on datamining everything myself lately ([currently viewable here](https://lothrik.github.io/diablo4-build-calc/parser/other/)) as I don't really want to rely on someone else's datamining efforts to keep this calculator working.

>Is it publicly available somewhere or did you put this all together on your own?

No datamining tools are currently publicly available, to the best of my knowledge. I haven't released mine, anyway; and I don't think the guy that sent me those skill tree JSON exports has either.

If for whatever reason I stop working on this build calculator I'll upload the tools I used here.

**Comment by heivo** [comment]
Thanks alot for those infos. I was hoping that Blizzard shares this data with community tool creators like [Grinding Gear Games did for PoE](https://github.com/grindinggear/skilltree-export).

**Comment by reallucky84** [comment]
Thanks for your work. I'm thinking of mining myself also. 
but I'm new to data mining on games.
Is there any tips or tricks?

**Comment by mfloob** [comment]
He won't give you extracting methods because he thinks he can scum money out of you. Look at [my repository](https://github.com/mfloob/diablo4-data-harvest) or [d4 string parser](https://github.com/alkhdaniel/diablo-4-string-parser) to see how he gets the data.

**Comment by Lothrik** [comment]
> He won't give you extracting methods because he thinks he can scum money out of you for his Patreon.

Seriously? I spent hundreds of hours on this. I wasn't obligated to make *any* of this open source, never mind MIT license it.

If I gave a shit about money I would have just sold the entire project to one of the two different groups of people that have tried to **buy out this project** out so they can put it behind walls of advertising and subscriptions.

I put a Patreon up specifically so people would stop asking me to monetize it. You literally don't even get anything for subscribing. Get the fuck out of here, man.

**Comment by GeoffMcLennan** [comment]
Didn't mean to start drama! I very much appreciate anybody who creates open source software and you definitely deserve the right to have compensation for your work! I was just hoping to get more info on the underlying datamining so I could develop my own tools to share with the community
