### ISSUE TITLE
I have a requirement.

### ISSUE THREAD

**Issue by qlife1146** [Lothrik/diablo4-build-calc#10]
1. On top of Diablo's enhanced skills, you choose one of the two. But I think it's very inefficient to press the one you've already clicked to release it again and press the other one. I think it's better to automatically release the clicked one when you click the one that's turned off.
2. In order to add Korean with my lack of skills, I added a drop-down menu to html, found value in the js file, and tried to import Korean translated data.js, but the function I wrote in onchage doesn't work in main.js. Do you happen to know the cause?
```
//index.html
	<div id="footer">
		...
		<select id="selectLang" onchange="selectedLang()">
			<option value="eng">English</option>
			<option value="kor">Korean</option>
		</select>
	</div>

//main.js
    ...
    function selectedLang() {
        let selectedLang = document.getElementById("selectLang").value;
         console.log(selectedLang);
        //error: Uncaught ReferenceError: selectedLang is not defined at HTMLSelectElement.onchange
    }
    ...
```

**Comment by Lothrik** [comment]
I just implemented your node swapping request. Test it out and let me know if it works for you.

For the second part your ``selectedLang()`` function doesn't exist in that context &mdash; you need to attach it to the select element via javascript instead.

```
// index.html
<div id="footer">
	...
	<select id="selectLang" onchange="selectedLang()">
		<option value="eng">English</option>
		<option value="kor">Korean</option>
	</select>
</div>

// main.js
document.getElementById("selectLang").addEventListener("change", selectedLang);
function selectedLang() {
    console.log(this.value);
}
```

**Comment by qlife1146** [comment]
thank you. I'll test later.

**Comment by qlife1146** [comment]
1. Awesome, It's More Convenient!
2. I wrote the code as follows but it doesn't work as I thought. Are there any mistakes?
```
// import { barbarianData } from "./data/barbarian.js";
...
document.getElementById("selectLang").addEventListener("change", selectLanguage);
async function selectLanguage(){
	// console.log(this.value);
	let barbarianData;
	if(this.value === "eng") {
		barbarianData = await import("./data/barbarian.js");
	} else {
		barbarianData = await import("./data/kor/barbarian_kor.js");
	}
	console.log(barbarianData);
}
```
Clearing the top barbarianData and importing it from the async function ensures that console.log imports the data correctly, but the cannvasContainer's job selection disappears.

**Comment by qlife1146** [comment]
I tried this code.
```
document.getElementById("selectLang").addEventListener("change", selectLanguage);
function selectLanguage(){
	if(this.value === "eng") {
		classObj["barbarian"] = barbarianData;
	} else if (this.value === "kor") {
		classObj["barbarian"] = barbarianDataKor;
	}
	console.log(this.value);
	console.log(classObj["barbarian"]);
}
```

**Comment by Lothrik** [comment]
Honestly, dynamic language hot swapping isn't really a feature you're going to be able to add with a few lines of code. Something involving cookies (where you reload the entire page whenever the language changes) would likely be much easier to implement. This is most likely wasted effort on your part though; Diablo 4 supports 13 different languages, I just haven't exported all of them yet.

**Comment by qlife1146** [comment]
Instead of the dropdown menu, will you copy and translate all the files you currently configure into a tag called '[Kor]' and accept it if I pull request?
```
mainPage → [Eng] → Original Page
    ↓
    →    → [Kor]  → Translated Page
```

**Comment by Lothrik** [comment]
This should (mostly) be resolved, as localization is now available.
