### ISSUE TITLE
Paragon Board Labeling

### ISSUE THREAD

**Issue by Daagni** [Lothrik/diablo4-build-calc#14]
On the starter board for paragon for druid, on the left bottom corner is labeled as Barbarian_Rare_015. 
![Druid Rare Missing](https://user-images.githubusercontent.com/60052290/231031790-6cdc094e-902e-4fd1-9fb7-42133d71bd25.jpg)

**Comment by Lothrik** [comment]
This is a bug in Blizzard's data, not something I can fix.
