### ISSUE TITLE
Movement of Paragon Tiles

### ISSUE THREAD

**Issue by Daagni** [Lothrik/diablo4-build-calc#15]
Clicking the arrows to move the paragon board seems clunky, it gives what looks like array locations?  I had to scroll up to figure out what was going on.  I thought it had completely deleted the paragon board.  Possibly just making it move the array one time in the direction of the arrow clicked of its initial location would be better. 
![Paragon Board Movement](https://user-images.githubusercontent.com/60052290/231032679-d2ce182d-1b05-49af-a33e-2fbf48c1ab1c.jpg)

**Comment by Lothrik** [comment]
I added some explanation text to hopefully point people in the right direction:
![image](https://user-images.githubusercontent.com/18443616/231037189-1a9fa680-583e-498e-b633-b840f101d18b.png)

**Comment by Lothrik** [comment]
You can now also position paragon boards by allocating gate attachment nodes directly. If there is no board in that direction, a modal dialog window opens, allowing you to select your desired paragon board from a list.
