### ISSUE TITLE
When i open the project on Local Host its blank

### ISSUE THREAD

**Issue by matiusman356** [Lothrik/diablo4-build-calc#16]
![image](https://user-images.githubusercontent.com/55943372/233963221-6dfba3f0-387e-4dc8-8034-358ee56194db.png)
It shows blank screen when I open on local host. i see you typed its private in description but on top it says its public.
i am new to github. can you please tell me how it works.
Thanks

**Comment by Lothrik** [comment]
>It shows blank screen when I open on local host.

You need to either run a web server and open the configured port (ex: ``localhost:8000``):
```bat
cd ./diablo4-build-calc/
python -m http.server 8000
```

.. or open ``index.html`` in a browser with CORS disabled:

```
"[PATH_TO_CHROME]\chrome.exe" --disable-web-security --user-data-dir=%LOCALAPPDATA%\Google\chromeTemp
```

As opening ``index.html`` directly in a standard browser (as you've done in your screenshot) will result in numerous CORS errors:

```
Access to script at 'file:///[...].js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.
```

>i see you typed its private in description but on top it says its public.

I have no idea what you're referring to, here.
