### ISSUE TITLE
Is it possible to localize into other languages?

### ISSUE THREAD

**Issue by AlexRomanoid** [Lothrik/diablo4-build-calc#2]
Thanks for your work. I found your calculator through the discord community.
Will there be support for other languages in the future?

**Comment by Lothrik** [comment]
I'll look into supporting multiple languages once I'm able to export them from the game client. I only have access to the enUS text, currently.

**Comment by AlexRomanoid** [comment]
thanks for the answer

**Comment by Lothrik** [comment]
Just as a bit of a status update: I am still planning on doing this, it just demands a fair bit of time and I'm operating with essentially **negative** free time currently.

**Comment by Lothrik** [comment]
I had some time to work on this recently, and made decent progress:
![image](https://user-images.githubusercontent.com/18443616/236395548-206a1efa-85bc-402c-aea6-7862c9c9df93.png)

![image](https://user-images.githubusercontent.com/18443616/236395888-b8a4abe7-8e0d-42db-b5c2-9285d3b0385b.png)

![image](https://user-images.githubusercontent.com/18443616/236396185-4cca9cea-6439-4737-b87a-565e75bdad3c.png)

Soon? Maybe.

**Comment by Lothrik** [comment]
This should (mostly) be resolved, as localization is now available.
