### ISSUE TITLE
Spiritual Power rare node on "Ancestral Guidance" board incorrect

### ISSUE THREAD

**Issue by NekotTheBrave** [Lothrik/diablo4-build-calc#31]
At the moment the Spiritual Power rare node on the "Ancestral Guidance" provides incorrect or insufficient information.

The tootip says:
"
14% Basic Skill Damage
Bonus: Another 14% Basic Skill Damage if requirements met:
{220+(130 * EquipIndex)} Willpower
{170+(90 * EquipIndex)} Intelligence

Tags: Core, Damage, Basic
"
The node *should* provide both Basic & Core skill damage. The basic being around 33.5% and the core being 14%. It has the correct bonus interaction, but has the wrong value since it should be an additional 33.5% basic damage. But regardless, it's just missing it's 2nd stat value like all the other rare nodes have.
![lothrik](https://github.com/Lothrik/diablo4-build-calc/assets/67830152/fe8154e0-8292-4c0c-877c-51c1e4dcdf15)

**Comment by Lothrik** [comment]
Thanks for reporting this. I found the root cause and fixed the problem. It turns out there was a (very rare) index collision bug with my paragon node parsing.
