### ISSUE TITLE
Request: "reset Paragon board" button

### ISSUE THREAD

**Issue by FBrebion** [Lothrik/diablo4-build-calc#33]
At the moment you can reset everything (the entire board + skill tree) but if you want to experiment with multiple Paragon boards, you have to recreate the skill tree from scratch all the time which isn't too practical. There's a button to reset individual boards but it doesn't make them move back to their initial position besides the Start board.

**Comment by Lothrik** [comment]
I added a button that fully resets everything related to the paragon board.

![image](https://github.com/Lothrik/diablo4-build-calc/assets/18443616/2e161568-9b6a-490b-b256-7995ff4501b7)
