### ISSUE TITLE
Database info

### ISSUE THREAD

**Issue by jhlfergus** [Lothrik/diablo4-build-calc#42]
Hey! I appreciate what you have done with the D4 calculator. I am trying to take your info and place it into a CSV and have the least amount of manual editing as possible so that I can quickly access the data when patches are released, etc. What is the best way to do that? Or do you have an API that I can use to pull this info? Basically I want the ability to select items from the skill tree and paragon board but from within Excel. I'm a number cruncher but want the app to do the crunching as well then compare the results. Any ideas for this? Really appreciate you either way but thought I would ask.

**Comment by Lothrik** [comment]
Sorry, there is no API for this. Just the [raw JSON data](https://github.com/Lothrik/diablo4-build-calc/tree/master/database), [a web-based viewer](https://lothrik.github.io/diablo4-build-calc/database/), and auto-generated [version history](https://lothrik.github.io/diablo4-build-calc/history).

If you want something more comprehensive I suggest checking out [Nishimura-Katsuo's project](https://github.com/blizzhackers/d4data/). It's actually intended to cover all file formats and be broadly applicable, unlike my database, which was created specifically for my build calculator out of necessity, as nothing else was available when I started this.

I'm not really sure where they're most active, I've only ever talked to them in [this discord server](https://discord.com/invite/d4cowlevel).
