### ISSUE TITLE
Starting paragon boards seem incomplete

### ISSUE THREAD

**Issue by john-riordan** [Lothrik/diablo4-build-calc#6]
I've been exploring your db data have noticed that the starting paragon boards are missing data. The typical board is 21x21 but the starting is only 15

starting
![image](https://user-images.githubusercontent.com/2053906/226738578-86f5fe34-d510-40a8-aa98-c34eb0d93f0f.png)

typical board
![image](https://user-images.githubusercontent.com/2053906/226738640-6a9d077c-184c-4166-a87e-e285963232f3.png)

**Comment by Lothrik** [comment]
I'm parsing the starting paragon boards exactly the same way as the other ones, they just don't have any data past the 15th row. They literally just looks like this in the raw file:

![image](https://user-images.githubusercontent.com/18443616/226782567-278ec186-4b86-4d7d-b11e-caa72f986080.png)


As for detached/impossible to allocate nodes; I'm not sure what you're referring to, as I don't see any of those in my data or calculator.

Example ASCII grid for ``Paragon_Barb_00``:
```
_,_,_,_,_,_,_,_,_,_,N,_,_,_,_,_,_,_,_,_,_
_,_,_,_,_,_,_,_,_,N,N,N,_,_,_,_,_,_,_,_,_
_,_,_,_,_,_,_,_,_,N,_,N,_,_,_,_,_,_,_,_,_
_,_,_,_,_,_,_,_,_,N,_,N,_,_,_,_,_,_,_,_,_
_,_,_,_,_,_,_,_,N,N,_,N,N,_,_,_,_,_,_,_,_
_,_,_,_,_,_,_,N,N,N,_,N,N,N,_,_,_,_,_,_,_
_,_,_,_,_,_,N,N,N,N,N,N,N,N,N,_,_,_,_,_,_
_,_,_,_,_,_,_,N,N,N,N,N,N,N,_,_,_,_,_,_,_
_,_,_,_,_,_,_,_,N,N,N,N,N,_,_,_,_,_,_,_,_
_,_,_,_,_,_,_,_,_,N,_,N,_,_,_,_,_,_,_,_,_
_,_,_,_,_,_,_,_,N,N,_,N,N,_,_,_,_,_,_,_,_
_,_,_,_,_,_,_,_,N,N,_,N,N,_,_,_,_,_,_,_,_
_,_,_,_,_,_,_,_,N,_,_,_,N,_,_,_,_,_,_,_,_
_,_,_,_,_,_,_,_,N,N,N,N,N,_,_,_,_,_,_,_,_
_,_,_,_,_,_,_,_,_,N,N,N,_,_,_,_,_,_,_,_,_
```

**Comment by Lothrik** [comment]
``Generic_Magic_Armor`` is missing from the node table because the ``.stl`` file is essentially completely empty. It just has a header and then null bytes, so I don't have anything worth putting in the JSON currently. In that case you just have to take the key in the Paragon Board data literally.

See:
![image](https://user-images.githubusercontent.com/18443616/226825661-4a606e91-3755-4bdf-a58b-88923d9c9731.png)

You are correct that the starting board is 21x21. The bottom 6 rows are just excluded from the JSON as they're completely empty.

**Comment by john-riordan** [comment]
Not only the bottom 6 rows but also the edges. I played the closed alpha and you should be starting in the middle with gates on all 4 sides but the data doesn't seem to have that so we'll see.

**Comment by john-riordan** [comment]
I'm positive, I even wrote down the exact node structure for the Sorc staring board in a private repo months ago. There isn't even a starting point (which should be the direct center). So unless they changed it from the friends and family alpha, where do you even start on that board? And it only has one gate so you're forced the travel upwards? The alpha I played you start in the center and it otherwise looks like the other boards (gate at the center of each side, exactly like how they [detailed in their post](https://bnetcmsus-a.akamaihd.net/cms/page_media/2RGSZ7OJGHB11639765827279.png)). If this data is correct the only thing I can see is starting at the bottom center I guess ([10][15])?
