### ISSUE TITLE
How do I spin this up locally?

### ISSUE THREAD

**Issue by cmarabate** [Lothrik/diablo4-build-calc#8]
Can you explain how to spin this repo up locally? I am confused by the lack of a package.json file. Normally I can use yarn to install all the packages and then use **yarn start** to spin it up.

What am I missing?

**Comment by Lothrik** [comment]
There shouldn't be any packages required. Just launch any web server with ``diablo4-build-calc`` as the root directory.

```
cd ./diablo4-build-calc/
python3 -m http.server 8000
```

**Comment by cmarabate** [comment]
Oh okay, that is very different from what I am used to. Thanks!
